packages:
  - .

allowBuilds:
  core-js: set this to true or false
  esbuild: true
  highlight.js: set this to true or false
  vuepress: set this to true or false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
